### ISSUE TITLE
Fails if there are any non *.go files in the directory

### ISSUE THREAD

**Issue by jimeh** [micvbang/go-mocky#1]
I haven't had a chance to poke around the code yet, but figured I'd report an issue for now at least.

```
$ mocky -i Runner
2022/06/02 01:15:14 failed to generate mocks: failed to parse dir /Users/jimeh/Projects/go-runner: -: named files must be .go files: /Users/jimeh/Projects/go-runner/.gitignore
```

**Comment by micvbang** [comment]
Thanks a lot for reporting this! I've just pushed a fix.

It's definitely on the TODO to write some tests in general :relaxed: 

EDIT: please let me know if the new commits fixed it for you :)
